# Generated by Django 3.1.4 on 2020-12-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
